# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAa():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aa(self):
    self.driver.get("https://www.linkedin.com/jobs/search/?currentJobId=3912090685&distance=25&f_E=2&f_JT=F&f_TPR=r2592000&geoId=105214831&keywords=Data%20Science&location=Bengaluru")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.LINK_TEXT, "Skills: Amazon Redshift, Extract, Transform, Load (ETL), +8 more").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ph5:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".job-details-how-you-match__tip-wrapper--freemium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-body-small:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ivm-view-attr__icon--signal-neutral").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex-column > .t-bold").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex-column > .t-bold").click()
    self.driver.find_element(By.LINK_TEXT, "Airflow, Amazon Redshift, Computer Science, Data Engineering, Databases, Datasets, Extract, Transform, Load (ETL), PostgreSQL, Relational Databases, and Technical Architecture").click()
    element = self.driver.find_element(By.LINK_TEXT, "Airflow, Amazon Redshift, Computer Science, Data Engineering, Databases, Datasets, Extract, Transform, Load (ETL), PostgreSQL, Relational Databases, and Technical Architecture")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#ember388 use").click()
  
